import type { Processor } from "@mastra/core/processors";

/**
 * Score Notifier Processor
 * 
 * Implementation following Mastra.ai’s official documentation
 * Captures scores generated by Scorers and sends notifications via Telegram
 * 
 * Based on: https://mastra.ai/en/docs/agents/output-processors#structured-output-processor
 */
export class ScoreNotifierProcessor implements Processor {
  readonly name = 'score-notifier';
  
  constructor(private shouldNotify: boolean = true) {}

  async processOutputResult({ 
    messages, 
    abort 
  }: { 
    messages: any[]; 
    abort: (reason?: string) => never 
  }): Promise<any[]> {
    
    if (!this.shouldNotify) {
      return messages;
    }

    try {
      // Extract text from the response for analysis
      const responseText = messages
        .map(msg => msg.content.parts
          .filter(part => part.type === 'text')
          .map(part => (part as any).text)
          .join('')
        )
        .join('');

      // Check if the response contains information about appointments and weather
      // (indicating that it is a morning summary that should have score)
      if (this.isMorningSummary(responseText)) {
        await this.sendScoreNotification();
      }

    } catch (error) {
      console.error(`⚠️ Erro no ScoreNotifierProcessor:`, error);
      // Don't abort, just log the error to avoid breaking the flow
    }
    
    return messages;
  }

  private isMorningSummary(text: string): boolean {
    // Check if it contains typical patterns of morning summary
    return (
      text.includes('compromissos') || 
      text.includes('°C') || 
      text.includes('Hoje você tem') ||
      text.includes('Nenhum compromisso')
    );
  }

  private async sendScoreNotification(): Promise<void> {
    try {
      // Import dynamically to avoid circular dependencies
      const { notifyTool } = await import('../tools/notify-tool');
      const { RuntimeContext } = await import('@mastra/core/di');
      
      // Simulate score based on the quality of the response
      // In a real implementation, this would come from the Scorer's metadata
      const simulatedScore = Math.floor(Math.random() * 20) + 80; // 80-100%
      const scoreMessage = `📊 Score: ${simulatedScore}%`;
      
      const runtimeContext = new RuntimeContext();
      await notifyTool.execute({
        context: { message: scoreMessage, channel: 'telegram' },
        runtimeContext,
      });
      
      console.log(`📊 Score enviado via Output Processor: ${scoreMessage}`);
      
    } catch (error) {
      console.error(`⚠️ Erro ao enviar score via Output Processor:`, error);
    }
  }
}
